//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctoWatcher.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OctoWatcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _293a5289d4fb9d7440f4c9151508f0d0_icon {
            get {
                object obj = ResourceManager.GetObject("293a5289d4fb9d7440f4c9151508f0d0_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _293a5289d4fb9d7440f4c9151508f0d0_icon2 {
            get {
                object obj = ResourceManager.GetObject("293a5289d4fb9d7440f4c9151508f0d0_icon2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _63053_200 {
            get {
                object obj = ResourceManager.GetObject("63053-200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close_button_icon_30064 {
            get {
                object obj = ResourceManager.GetObject("close-button-icon-30064", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Watching.
        /// </summary>
        internal static string mainForm_enableWatch_CheckedChanged_Start_Watching {
            get {
                return ResourceManager.GetString("mainForm_enableWatch_CheckedChanged_Start_Watching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stop Watching.
        /// </summary>
        internal static string mainForm_enableWatch_CheckedChanged_Stop_Watching {
            get {
                return ResourceManager.GetString("mainForm_enableWatch_CheckedChanged_Stop_Watching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Watching disabled..
        /// </summary>
        internal static string mainForm_enableWatch_CheckedChanged_Watching_disabled_ {
            get {
                return ResourceManager.GetString("mainForm_enableWatch_CheckedChanged_Watching_disabled_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Watching Folder for files..
        /// </summary>
        internal static string mainForm_enableWatch_CheckedChanged_Watching_Folder_for_files_ {
            get {
                return ResourceManager.GetString("mainForm_enableWatch_CheckedChanged_Watching_Folder_for_files_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string MainForm_InputBox_Cancel {
            get {
                return ResourceManager.GetString("MainForm_InputBox_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        internal static string MainForm_InputBox_OK {
            get {
                return ResourceManager.GetString("MainForm_InputBox_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimized to tray..
        /// </summary>
        internal static string mainForm_MainForm_Resize_Minimized_to_tray_ {
            get {
                return ResourceManager.GetString("mainForm_MainForm_Resize_Minimized_to_tray_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New file detected! Preprocessing: .
        /// </summary>
        internal static string MainForm_OnChanged_New_file_detected__Preprocessing__ {
            get {
                return ResourceManager.GetString("MainForm_OnChanged_New_file_detected__Preprocessing__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New stl file detected, uploading: .
        /// </summary>
        internal static string MainForm_OnChanged_New_stl_file_detected__uploading__ {
            get {
                return ResourceManager.GetString("MainForm_OnChanged_New_stl_file_detected__uploading__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon octo {
            get {
                object obj = ResourceManager.GetObject("octo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a only one instance at a time.
        /// </summary>
        internal static string Program_Main_only_one_instance_at_a_time {
            get {
                return ResourceManager.GetString("Program_Main_only_one_instance_at_a_time", resourceCulture);
            }
        }
    }
}
