//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctoWatcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OctoWatcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _293a5289d4fb9d7440f4c9151508f0d0_icon {
            get {
                object obj = ResourceManager.GetObject("293a5289d4fb9d7440f4c9151508f0d0_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _293a5289d4fb9d7440f4c9151508f0d0_icon2 {
            get {
                object obj = ResourceManager.GetObject("293a5289d4fb9d7440f4c9151508f0d0_icon2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _63053_200 {
            get {
                object obj = ResourceManager.GetObject("63053-200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close_button_icon_30064 {
            get {
                object obj = ResourceManager.GetObject("close-button-icon-30064", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Watching.
        /// </summary>
        internal static string mainForm_enableWatch_CheckedChanged_Start_Watching {
            get {
                return ResourceManager.GetString("mainForm_enableWatch_CheckedChanged_Start_Watching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Watching.
        /// </summary>
        internal static string mainForm_enableWatch_CheckedChanged_Stop_Watching {
            get {
                return ResourceManager.GetString("mainForm_enableWatch_CheckedChanged_Stop_Watching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching disabled..
        /// </summary>
        internal static string mainForm_enableWatch_CheckedChanged_Watching_disabled_ {
            get {
                return ResourceManager.GetString("mainForm_enableWatch_CheckedChanged_Watching_disabled_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching Folder for files..
        /// </summary>
        internal static string mainForm_enableWatch_CheckedChanged_Watching_Folder_for_files_ {
            get {
                return ResourceManager.GetString("mainForm_enableWatch_CheckedChanged_Watching_Folder_for_files_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MainForm_InputBox_Cancel {
            get {
                return ResourceManager.GetString("MainForm_InputBox_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MainForm_InputBox_OK {
            get {
                return ResourceManager.GetString("MainForm_InputBox_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimized to tray..
        /// </summary>
        internal static string mainForm_MainForm_Resize_Minimized_to_tray_ {
            get {
                return ResourceManager.GetString("mainForm_MainForm_Resize_Minimized_to_tray_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file detected! Preprocessing: .
        /// </summary>
        internal static string MainForm_OnChanged_New_file_detected__Preprocessing__ {
            get {
                return ResourceManager.GetString("MainForm_OnChanged_New_file_detected__Preprocessing__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New stl file detected, uploading: .
        /// </summary>
        internal static string MainForm_OnChanged_New_stl_file_detected__uploading__ {
            get {
                return ResourceManager.GetString("MainForm_OnChanged_New_stl_file_detected__uploading__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon octo {
            get {
                object obj = ResourceManager.GetObject("octo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only one instance at a time.
        /// </summary>
        internal static string Program_Main_only_one_instance_at_a_time {
            get {
                return ResourceManager.GetString("Program_Main_only_one_instance_at_a_time", resourceCulture);
            }
        }
    }
}
